version: "3.9"

services:
    data-source:
        container_name: data-source
        build:
            context: .
            dockerfile: ./data-source/Dockerfile
        env_file:
            - ./data-source/.env
        expose:
            - 5000/tcp
        command: yarn start

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
            - mongo_data:/data/db
        env_file:
            - ./mongo/.env

    gateway:
        container_name: gateway
        build:
            context: .
            dockerfile: ./gateway/Dockerfile
        env_file:
            - ./gateway/.env
        ports:
            - ${API_GATEWAY_PORT:-8001}:3000
        depends_on:
            mongo:
                condition: service_started
        command: yarn start

    web-app:
        container_name: web-app
        build:
            context: .
            dockerfile: ./web-app/Dockerfile
        environment:
            - NEXT_PRIVATE_API=http://gateway:3000
            - NEXT_PUBLIC_API=http://localhost:${API_GATEWAY_PORT:-8001}
        ports:
            - ${WEB_APP_PORT:-8000}:3000
        entrypoint: [ "/bin/sh", "-c" ]
        command:
            - |
                yarn build
                yarn start

volumes:
    mongo_data:
